export const starterMsg = [
  "You’re off to great places, today is your day. Your mountain is waiting, so get on your way.-Dr. Seuss",
  "You always pass failure on the way to success. -Mickey Rooney",
  "No one is perfect - that’s why pencils have erasers. -Wolfgang Riebe",
  "You’re braver than you believe, and stronger than you seem, and smarter than you think. -A.A. Mine",
  "It always seems impossible until it is done. -Nelson Mandela",
  "Keep your face to the sunshine and you cannot see a shadow. -Helen Keller",
  "Once you replace negative thoughts with positive ones, you’ll start having positive results. -Willie Nelson",
  "Positive thinking will let you do everything better than negative thinking will. -Zig Ziglar",
  "In every day, there are 1,440 minutes. That means we have 1,440 daily opportunities to make a positive impact. -Les Brown",
  "The only time you fail is when you fall down and stay down. -Stephen Richards",
  "Positive anything is better than negative nothing. -Elbert Hubbard",
  "Winning is fun, but those moments that you can touch someone’s life in a very positive way are better. -Tim Howard",
  "Optimism is a happiness magnet. If you stay positive good things and good people will be drawn to you. -Mary Lou Retton",
  "It makes a big difference in your life when you stay positive. -Ellen DeGeneres",
  "If opportunity doesn’t knock, build a door. -Milton Berle",
  "You are never too old to set another goal or dream a new dream. -Les Brown",
  "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on. -Charles Dickens",
  "It’s not whether you get knocked down, it’s whether you get up. -Vince Lombardi",
  "The struggle you’re in today is developing the strength you need tomorrow. -Robert Tew",
  "Every day may not be good... but there’s something good in every day. -Alice Morse Earle",
  "The difference between ordinary and extraordinary is that little extra. -Jimmy Johnson",
  "Success is the sum of small efforts repeated day in and day out. -Robert Collier",
  "Happiness is the only thing that multiplies when you share it. -Albert Schweitzer"
];
